/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * ????
 * @export
 * @interface MemberAndNumberOfFinishTasksForm
 */
export interface MemberAndNumberOfFinishTasksForm {
    /**
     * 
     * @type {number}
     * @memberof MemberAndNumberOfFinishTasksForm
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof MemberAndNumberOfFinishTasksForm
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof MemberAndNumberOfFinishTasksForm
     */
    numOfFinishedTasks: number;
}
