/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * ????
 * @export
 * @interface ProjectMemberInfoForm
 */
export interface ProjectMemberInfoForm {
    /**
     * 
     * @type {number}
     * @memberof ProjectMemberInfoForm
     */
    projectId: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectMemberInfoForm
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberInfoForm
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectMemberInfoForm
     */
    role: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectMemberInfoForm
     */
    relationshipId: number;
}
