/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TaskVO
 */
export interface TaskVO {
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    priority: number;
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    state: number;
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    createUserId: number;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    createTime: string;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    updateTime: string;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    estimateCompleteTime: string;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    completeTime: string;
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    taskListId: number;
    /**
     * 
     * @type {number}
     * @memberof TaskVO
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof TaskVO
     */
    content: string;
}
