/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TaskVO } from './task-vo';
/**
 * ????
 * @export
 * @interface TaskListVO
 */
export interface TaskListVO {
    /**
     * 
     * @type {number}
     * @memberof TaskListVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TaskListVO
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TaskListVO
     */
    projectId: number;
    /**
     * 
     * @type {Array<TaskVO>}
     * @memberof TaskListVO
     */
    tasks: Array<TaskVO>;
}
